import { StyleSheet } from 'react-native';
import { colors, type, spacing, radius, shadows } from './welcome.styles';

export { colors, type, spacing, radius, shadows };

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.ink, // hero sits flush at the top, no seam
  },
  scrollContent: {
    flexGrow: 1,
  },

  // --- Hero panel ---
  hero: {
    backgroundColor: colors.ink,
    paddingBottom: 44,
    overflow: 'hidden',
  },
  heroAccentRing: {
    position: 'absolute',
    borderRadius: 999,
    backgroundColor: colors.periwinkle,
    opacity: 0.12,
  },
  heroAccentRingSmall: {
    position: 'absolute',
    borderRadius: 999,
    backgroundColor: colors.marigold,
    opacity: 0.08,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: spacing.lg + 4,
  },
  heroEyebrow: {
    ...type.overline,
    color: 'rgba(251,247,239,0.5)',
    marginBottom: spacing.xxs,
    letterSpacing: 1.2,
  },
  pageTitle: {
    ...type.h1,
    fontSize: 30,
    letterSpacing: -0.5,
    color: colors.paper,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 10,
  },
  addButton: {
    width: 42,
    height: 42,
    borderRadius: radius.pill,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonPressed: {
    opacity: 0.7,
    transform: [{ scale: 0.94 }],
  },
  addButtonPrimary: {
    backgroundColor: colors.marigold,
    borderColor: colors.marigold,
    ...shadows.soft,
  },

  // --- Day tabs, on-dark ---
  dayTabRow: {
    flexDirection: 'row',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.05)',
    padding: 4,
    borderRadius: radius.lg,
  },
  dayTab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: radius.md,
  },
  dayTabPressed: {
    opacity: 0.75,
  },
  dayTabActive: {
    backgroundColor: colors.marigold,
    ...shadows.soft,
  },
  dayTabLabel: {
    ...type.caption,
    fontSize: 10.5,
    color: 'rgba(251,247,239,0.55)',
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  dayTabLabelActive: {
    color: colors.marigoldInk,
  },
  dayTabNumber: {
    ...type.label,
    fontSize: 16,
    color: colors.paper,
    marginTop: 3,
    fontWeight: '700',
  },
  dayTabNumberActive: {
    color: colors.marigoldInk,
  },
  dayTabTodayDot: {
    position: 'absolute',
    top: 7,
    right: '50%',
    marginRight: -14,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.marigold,
  },

  // --- Content sheet ---
  contentSheet: {
    flex: 1,
    backgroundColor: colors.paper,
    borderTopLeftRadius: radius.lg + 10,
    borderTopRightRadius: radius.lg + 10,
    marginTop: -28,
    paddingTop: spacing.lg + 4,
    ...shadows.cta,
    shadowOpacity: 0.1,
  },
  sheetGrabber: {
    alignSelf: 'center',
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
    marginBottom: spacing.md,
  },
  sheetHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  sheetHeaderTitle: {
    ...type.h2,
    color: colors.ink,
    letterSpacing: -0.3,
  },
  sheetHeaderCount: {
    ...type.caption,
    color: colors.inkSoft,
    backgroundColor: colors.paperRaised,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radius.pill,
    overflow: 'hidden',
  },

  emptyCard: {
    backgroundColor: colors.paperRaised,
    borderRadius: radius.lg,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderStyle: 'dashed',
    paddingVertical: spacing.xl + 8,
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  emptyIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  emptyText: { ...type.body, fontSize: 14, color: colors.inkFaint, textAlign: 'center' },
  emptyCta: {
    marginTop: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.ink,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: radius.pill,
  },
  emptyCtaText: {
    ...type.label,
    fontSize: 13,
    color: colors.paper,
  },

  // --- Live Indicator Banner ---
  liveBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.md,
    borderRadius: radius.lg,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.04)',
    ...shadows.soft,
  },
  liveBannerPulse: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(255,255,255,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
  },
  liveBannerDot: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
  },
  liveBannerTitle: {
    ...type.caption,
    fontWeight: '800',
    fontSize: 10.5,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  liveBannerSubject: {
    ...type.label,
    fontSize: 14,
    color: colors.ink,
    marginTop: 3,
  },
  liveBannerTime: {
    ...type.caption,
    fontSize: 12,
    fontWeight: '700',
    color: colors.inkSoft,
  },

  // --- Grid View Timetable ---
  gridContainer: {
    marginTop: spacing.md,
    backgroundColor: colors.paperRaised,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    ...shadows.soft,
  },
  gridInner: {
    flexDirection: 'row',
  },
  timeColumn: {
    width: 58,
    borderRightWidth: 1,
    borderRightColor: colors.border,
    backgroundColor: colors.paper,
  },
  timeLabelContainer: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 8,
  },
  timeLabel: {
    ...type.caption,
    fontSize: 9.5,
    fontWeight: '600',
    color: colors.inkSoft,
  },
  classesColumn: {
    flex: 1,
    position: 'relative',
  },
  gridLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: colors.border,
    opacity: 0.5,
  },
  classBlock: {
    position: 'absolute',
    left: 8,
    right: 8,
    borderRadius: radius.md,
    padding: 10,
    overflow: 'hidden',
    gap: 3,
    justifyContent: 'center',
  },
  classBlockPressed: {
    transform: [{ scale: 0.98 }],
  },
  classBlockAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
  },
  classBlockHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  classBlockSubject: {
    ...type.label,
    fontSize: 15,
    fontWeight: '800',
    color: '#132A4C',
    flexShrink: 1,
  },
  classBlockLocation: {
    ...type.caption,
    fontSize: 12.5,
    fontWeight: '600',
    color: 'rgba(19,42,76,0.78)',
  },
  classBlockTime: {
    ...type.caption,
    fontSize: 11.5,
    fontWeight: '700',
    color: 'rgba(19,42,76,0.6)',
  },
  // --- Current Time Indicator ---
  currentTimeLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: colors.marigold,
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  currentTimeDot: {
    position: 'absolute',
    left: -4,
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: colors.marigold,
    borderWidth: 2,
    borderColor: colors.paper,
  },

  // --- Class Details Modal ---
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(19,42,76,0.55)',
  },
  modalContent: {
    backgroundColor: colors.paper,
    borderTopLeftRadius: radius.xl + 4,
    borderTopRightRadius: radius.xl + 4,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    ...shadows.cta,
  },
  modalGrabber: {
    alignSelf: 'center',
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
    marginBottom: spacing.lg,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.lg,
    gap: spacing.sm,
  },
  modalIconBadge: {
    width: 46,
    height: 46,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalColorStrip: {
    width: 6,
    height: '100%',
    borderRadius: 3,
    marginRight: spacing.sm,
  },
  modalSubject: {
    ...type.h2,
    color: colors.ink,
    letterSpacing: -0.3,
  },
  modalTime: {
    ...type.caption,
    color: colors.inkSoft,
    marginTop: 2,
    fontWeight: '600',
  },
  modalCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.paperRaised,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBody: {
    backgroundColor: colors.paperRaised,
    borderRadius: radius.lg,
    padding: spacing.md,
    gap: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.lg,
  },
  modalDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  modalDetailIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.paper,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalDetailText: {
    ...type.body,
    fontSize: 15,
    color: colors.ink,
    flex: 1,
  },
  modalSectionTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.ink,
    marginBottom: spacing.sm,
    letterSpacing: 0.2,
  },
  modalListRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
    backgroundColor: colors.paperRaised,
    padding: 10,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.md,
    borderRadius: radius.md,
  },
  modalActionBtnPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.98 }],
  },
  modalActionText: {
    ...type.label,
  },
});